name: Update Demo Website
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node JS LTS
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install Brain.js Dependencies
      run: sudo apt-get install -y build-essential mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6

    - name: Install dependencies
      run: npm ci
      working-directory: ./website/

    - name: Run build steps
      run: npm run build -s
      working-directory: ./website/

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: website/dist